#!/bin/bash
set -euo pipefail

env() {
    OMZ_REPO="${MYZSH_REPO:-https://github.com/ohmyzsh/ohmyzsh}"
    MYZSH_REPO="${MYZSH_REPO:-https://github.com/mcmineleng/myzsh}"
    MYZSH_DIR="${MYZSH_DIR:-$HOME/.myzsh}"
    OMZ_THEMES_INSTALL="${OMZ_THEMES_INSTALL:-true}"
    OMZ_PLUGINS_INSTALL="${OMZ_PLUGINS_INSTALL:-true}"
}

cli() {
    read -p "\033[94mMyZsh仓库地址(回车默认): \033[0m" MYZSH_REPO
    read -p "\033[94mOh-My-Zsh仓库地址: \033[0m" OMZ_REPO
    read -p "\033[94m安装目录(默认\033[32m~/.myzsh\033[94m): \033[0m" MYZSH_DIR
    
    read -p "安装Oh-My-Zsh自带主题 [\033[32mY\033[94m/\033[31mn\033[94m] \033[0m" omz_install_themes
    omz_install_themes=${omz_install_themes:-Y}
    if [[ "$omz_install_themes" =~ ^[Yy]$ ]]; then
        OMZ_THEMES_INSTALL=true
    else
        OMZ_THEMES_INSTALL=false
    fi

    read -p "\033[94m安装Oh-My-Zsh自带插件 [\033[32mY\033[94m/\033[31mn\033[94m] \033[0m" omz_install_plugins
    omz_install_plugins=${omz_install_plugins:-Y}
    if [[ "$omz_install_plugins" =~ ^[Yy]$ ]]; then
        OMZ_PLUGINS_INSTALL=true
    else
        OMZ_PLUGINS_INSTALL=false
    fi
}

myzsh_install() {
    mkdir -p "$MYZSH_DIR"
    if [ $? -eq 0 ]; then
        echo "安装目录创建成功"
    else
        echo "\033[31m安装目录创建失败\033[0m"
        exit 1
    fi
    echo "正在克隆MyZsh仓库 · · ·"
    git clone --depth 1 "$MYZSH_REPO" "$MYZSH_DIR"
    if [ $? -eq 0 ]; then
        echo "克隆MyZsh仓库成功"
    else
        echo "\033[31m克隆MyZsh仓库失败\033[0m"
        exit 1
    fi
}

omz_clone() {
    mkdir -p "$MYZSH_DIR/.temp"
    if [ $? -eq 0 ]; then
        echo "临时目录创建成功"
    else
        echo "\033[31m临时目录创建失败\033[0m"
        exit 1
    fi
    echo "正在克隆Oh-My-Zsh仓库 · · ·"
    git clone --depth 1 "$OMZ_REPO" "$MYZSH_DIR/.temp/oh-my-zsh"
    if [ $? -eq 0 ]; then
        echo "克隆Oh-My-Zsh仓库成功"
    else
        echo "\033[31m克隆Oh-My-Zsh仓库失败\033[0m"
        exit 1
    fi
}

omz_themes_install() {
    echo "正在复制主题目录"
    if [[ -f "$MYZSH_DIR/.temp/oh-my-zsh/themes/random.zsh-theme" ]]; then
        rm "$MYZSH_DIR/.temp/oh-my-zsh/themes/random.zsh-theme"
    fi
    cp -r "$MYZSH_DIR/.temp/oh-my-zsh/themes" "$MYZSH_DIR/"
    if [ $? -eq 0 ]; then
        echo "主题目录复制成功"
    else
        echo "\033[31m主题目录复制失败\033[0m"
        exit 1
    fi
}

omz_plugins_install() {
    cp -r "$MYZSH_DIR/.temp/oh-my-zsh/plugins" "$MYZSH_DIR/"
    if [ $? -eq 0 ]; then
        echo "插件目录复制成功"
    else
        echo "\033[31m插件目录复制失败\033[0m"
        exit 1
    fi
}

write_zshrc() {
if [ ! -f ~/.zshrc ]; then
    touch ~/.zshrc
    if [ $? -eq 0 ]; then
        echo "~/.zshrc 创建成功"
    else
        echo "\033[31m~/.zshrc 创建失败\033[0m"
        exit 1
    fi
fi

cat >> ~/.zshrc << 'EOF'

MYZSH_DIR="$HOME/.myzsh"
source "$MYZSH_DIR/start/myzsh-load.sh"
EOF

if [ $? -eq 0 ]; then
    echo "~/.zshrc 写入成功"
else
    echo "\033[31m~/.zshrc 写入失败\033[0m"
    echo "请把下面的配置加入~/.zshrc"
    echo ""
    echo 'MYZSH_DIR="$HOME/.myzsh"
source'
    echo 'source "$MYZSH_DIR/start/myzsh-load.sh'
    echo ""
    exit 1
fi
}
temp_clear() {
    echo "正在清理临时目录"
    rm -rf "$MYZSH_DIR/.temp"
    if [ $? -eq 0 ]; then
        echo "临时目录清理成功"
    else
        echo "\033[31m临时目录清理失败\033[0m"
        exit 1
    fi
}

main() {
    if command -v git &> /dev/null; then
        :
    else
        echo "\033[31mGit 未安装，请安装之后继续\033[0m"
        exit 1
    fi
    if [[ " $* " == *" --cli "* ]]; then
        cli
    fi
    env
    myzsh_install
    if [[ "$OMZ_THEMES_INSTALL" == "true" ]] || [[ "$OMZ_PLUGINS_INSTALL" == "true" ]]; then
        omz_clone
    fi
    if [[ "$OMZ_THEMES_INSTALL" == "true" ]]; then
        omz_themes_install
    fi
    if [[ "$OMZ_PLUGINS_INSTALL" == "true" ]]; then
        omz_plugins_install
    fi
    write_zshrc
    temp_clear
    echo "安装完成，请使用:"
    echo "exec zsh"
    echo "重启zsh"
}

main "$@"
